### PR TITLE
use production env in cloud yml

### PR DESCRIPTION
**Pull request by tanner0101**

### CODE REVIEW

**Comment by 0xTim** [comment]
My concern with this is it forces the production environment for _all_ environments in Vapor Cloud. If Vapor Cloud could inject in the environment as a variable that would be better? Something like

```bash
run_parameters: "serve --port 8080 --hostname 0.0.0.0 --env $CLOUD_ENVIRONMENT"
```

Not sure if that's possible though @joscdk ?

**Comment by code28** [comment]
This is possible if you define your own config, i.e. your `cloud.yml` would look like this:
```yaml
[...]
run_parameters: "serve --port 8080 --hostname 0.0.0.0 --env $CLOUD_ENVIRONMENT"

config:
    production:
        CLOUD_ENVIRONMENT: "production"
    development:
        CLOUD_ENVIRONMENT: "development"
```

**Comment by joscdk** [comment]
No that's unfortunately not possible at the moment, as config variables aren't defined in the deploy process. This is on our roadmap to add this feature.

**Comment by 0xTim** [comment]
Closing due to the new `web.Dockerfile`

**Pull request closed without merging**
