### PR TITLE
Added update implementation / refactored comments for consistency

### PR DESCRIPTION
**Pull request by martinlasek**
I believe a simple example on how to decode a request using a struct alongside an implementation of `update` can give beginner more at their hands to work with :blush:

### CODE REVIEW

**Review by tanner0101 — APPROVED** [review]
Looks great, thanks @MartinLasek :)

**Review by loganwright — CHANGES_REQUESTED** [review]
@MartinLasek what was the reason for the move from `_ req:` to `req:`. since it's a strong type, maybe it's better to be implied, or possibly `with req` or something which is a pattern we use elsewhere. 

what do you think?

**Comment by martinlasek** [comment]
@loganwright honestly my thought was simply simplicity.
Since it seems to not matter whether we define our routes with or without the **underscore** I wanted to reduce the amount of code people who start out think they have to write. In addition to having to write less code it's also an additional comfort to leave the **underscore** out since that character compared to other characters on the keyboard is "harder" to reach. 😊 

I think that sums up the reason for the move. Feel free to disagree 😊 !

**Comment by 0xTim** [comment]
From a Swift API guidelines point of view, IMO the `_` makes sense, since you're passing in a `Request` type, that is probably called `request`, adding the additional parameter name is redundant

**Comment by martinlasek** [comment]
@0xTim Are you referring to other use cases than f.e:
```swift
router.get("user", controller.userList)
```
Since request is implicitly passed into our function and would work regardless of whether we have defined the `_` in `userList` or not. I thought why not going for the "without `_` definition". It would simplify the look (and potentially the understanding) of the template. I mean both works right. 😊 

Thinking: _"As much as necessary as little as possible (code)"_ 😊

**Comment by 0xTim** [comment]
No, more the case if you were to do

```swift
let response = controller.userList(request)
```
instead of
```swift
let response = controller.userList(req: request)
```

The `req` parameter name is redundant (depending on your interpretation of Swift's API Guidelines) since you're passing in a `Request` object.

**Comment by martinlasek** [comment]
I totally understand and don't like redundancy either 😊 
However I see/saw the api-template as a starting point where we don't have any usage of
```swift
let response = controller.userList(req: request)
```

We implement the benefit of underscore but aren't using it here. We could say that we should keep the **underscore** to guide beginners towards best practice. At the same time from the guidelines perspective we are not following the guidelines completely (f.e. no Setup folder). Maybe because we haven't catched up or maybe because we wanted to keep the api-template simple to start with. For the latter that was my origin to ditch the underscore in the template. 😊 

Ultimately I don't feel strong about it at all and consider getting the `update` endpoint merged in as more valuable than removing the underscore. If the **underscore** is the bottle neck here I'll happily update my PR to undo the removal 😊

**Comment by 0xTim** [comment]
Closing as this repo has been superseded by vapor/template - feel free to reopen on that repository if this PR still makes sense. Thanks for contributing!

**Pull request closed without merging**
