### PR TITLE
Adjust structure to support unit testing in Xcode

### PR DESCRIPTION
**Pull request by cwoloszynski**
I have adjusted the template to support unit testing in Xcode.  

A new module is created (AppLogic) and models and controllers are put in that module.

The package includes a new target with a dependency to support running the application in Xcode.

The package now does NOT exclude Tests.

The main.swift now includes the AppLogic package and then uses code in AppLogic to initialize the drop.

### CODE REVIEW

**Comment by tanner0101** [comment]
I'm not sure this is the correct approach. There are _so_ many different ways an app could be structured to include testing. And not all apps need testing.

Even if someone did start developing, then realize that they wanted tests, it would be really easy to move things over to a library module. It would just be a matter of dragging and dropping and maybe adding a couple of `public` access keywords.

I know we've wanted to add more templates such as `api-template`, `website-template`, `websockets-template`, etc. These could be better places to add library modules and testing.

I'd be interested for more opinions here, though. Anyone in @vapor/contributors care to chime in?

**Comment by rymcol** [comment]
I agree with @tannernelson -- and to add a little, we still have no information on how Xcode's future integration with SPM is going to work. It would probably be wise to keep the basics simple for now and move unit-testing to it's own example repo along with documentation specific to it.

**Comment by cwoloszynski** [comment]
@tanner

Thanks for taking a look at this approach.  I am new to Vapor (and loving it) but it took me (as a newbie) a fair amount of research to come up with a structure that would meet my needs and work within the automation of ‘vapor’.  I was very unclear about what types of changes could be made and how to get them to work within vapor and Xcode, but I suspect that the core team in Vapor is very comfortable with what can and cannot be done.  

If there is a better ‘starting’ approach to supporting testing, I am all for learning it and following that path.  But I would suggest that the basic templates include something to support testing in Xcode out of the box.  It will attract newbies and let those joining that testing is considered a first-class aspect of coding in vapor.

I look forward to watching and learning the best practices within Vapor for all of this.  

Thanks for the great tools and hard work and fantastic support you all give to us newbies!

Charlie

**Comment by tanner0101** [comment]
@cwoloszynski that's a good point. I'm sure those who are happy to have just gotten something working aren't really ready to start dragging and dropping files into different modules. :)

I think a good solution here would be a section in the documentation showcasing a few different ways for setting up tests for a vapor project.

Would any of you be interested in writing it?

**Comment by loganwright** [comment]
Just linking this here: vapor/vapor#667

**Comment by Casperhr** [comment]
This is now added to the doc
https://github.com/vapor/documentation/blob/master/testing/modules.md

**Pull request closed without merging**
