### PR TITLE
Updates for Swift 4

### PR DESCRIPTION
**Pull request by 0xTim**
I've also changed the keys slightly to make them a bit clearer and separate them out from the rest of the `Post` model

### CODE REVIEW

**Comment by gperdomor** [comment]
@0xTim I like the idea of the Keys in one place, the problem is when your model implements protocols like `Timestampable`, `SoftDeletable`, which implements his own keys... Also a model has an `idKey`... Like my friend buzz says:

76f50b750b03a836599ff24025ed70962b8d208d7055ec2a2f4c1b46988fc783

**Comment by gperdomor** [comment]
Also, can you put the `*+Setup.swift` files inside `App/Setup` folder please :D, and maybe `Routes.swift` inside a `Routes` folder, I think is more organized in that way

**Comment by 0xTim** [comment]
For the keys you can always add an extension to the `Keys` struct inside Post

**Comment by tanner0101** [comment]
looks great, thanks @0xTim!

**Pull request merged**
